# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 22:03
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg: +441234567890', max_length=128, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg: +447234567890', max_length=128, null=True)),
                ('work_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg: +441234567890', max_length=128, null=True)),
                ('website', models.URLField(blank=True, help_text='eg: http://www.example.com', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
