# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(null=True, blank=True, max_length=10, editable=False),
        ),
    ]
