# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 22:01
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
