# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:21
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('workmate', '0002_contact_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email_address', models.EmailField(max_length=254)),
                ('site', models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
