# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0004_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town'),
        ),
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, choices=[('Bath and North East Somerset', 'Bath and North East Somerset'), ('Bedford', 'Bedford'), ('Berkshire', 'Berkshire'), ('Blackburn with Darwen', 'Blackburn with Darwen'), ('Blackpool', 'Blackpool'), ('Bournemouth', 'Bournemouth'), ('Brighton & Hove', 'Brighton & Hove'), ('Bristol', 'Bristol'), ('Buckinghamshire', 'Buckinghamshire'), ('Cambridgeshire', 'Cambridgeshire'), ('Central Bedfordshire', 'Central Bedfordshire'), ('Cheshire East', 'Cheshire East'), ('Cheshire West and Chester', 'Cheshire West and Chester'), ('Cornwall', 'Cornwall'), ('Cumbria', 'Cumbria'), ('Darlington', 'Darlington'), ('Derby', 'Derby'), ('Derbyshire', 'Derbyshire'), ('Devon', 'Devon'), ('Dorset', 'Dorset'), ('Durham', 'Durham'), ('East Riding of Yorkshire', 'East Riding of Yorkshire'), ('East Sussex', 'East Sussex'), ('Essex', 'Essex'), ('Gloucestershire', 'Gloucestershire'), ('Greater Manchester', 'Greater Manchester'), ('Halton', 'Halton'), ('Hampshire', 'Hampshire'), ('Hartlepool', 'Hartlepool'), ('Herefordshire', 'Herefordshire'), ('Hertfordshire', 'Hertfordshire'), ('Isle of Wight', 'Isle of Wight'), ('Kent', 'Kent'), ('Kingston upon Hull', 'Kingston upon Hull'), ('Lancashire', 'Lancashire'), ('Leicester', 'Leicester'), ('Leicestershire', 'Leicestershire'), ('Lincolnshire', 'Lincolnshire'), ('London', 'London'), ('Luton', 'Luton'), ('Medway', 'Medway'), ('Merseyside', 'Merseyside'), ('Middlesbrough', 'Middlesbrough'), ('Milton Keynes', 'Milton Keynes'), ('Norfolk', 'Norfolk'), ('North East Lincolnshire', 'North East Lincolnshire'), ('North Lincolnshire', 'North Lincolnshire'), ('North Somerset', 'North Somerset'), ('North Yorkshire', 'North Yorkshire'), ('Northamptonshire', 'Northamptonshire'), ('Northumberland', 'Northumberland'), ('Nottingham', 'Nottingham'), ('Nottinghamshire', 'Nottinghamshire'), ('Oxfordshire', 'Oxfordshire'), ('Peterborough', 'Peterborough'), ('Plymouth', 'Plymouth'), ('Poole', 'Poole'), ('Portsmouth', 'Portsmouth'), ('Redcar and Cleveland', 'Redcar and Cleveland'), ('Rutland', 'Rutland'), ('Shropshire', 'Shropshire'), ('Somerset', 'Somerset'), ('South Gloucestershire', 'South Gloucestershire'), ('South Yorkshire', 'South Yorkshire'), ('Southampton', 'Southampton'), ('Southend-on-Sea', 'Southend-on-Sea'), ('Staffordshire', 'Staffordshire'), ('Stockton-on-Tees', 'Stockton-on-Tees'), ('Stoke-on-Trent', 'Stoke-on-Trent'), ('Suffolk', 'Suffolk'), ('Surrey', 'Surrey'), ('Swindon', 'Swindon'), ('Telford and Wrekin', 'Telford and Wrekin'), ('Thurrock', 'Thurrock'), ('Torbay', 'Torbay'), ('Tyne and Wear', 'Tyne and Wear'), ('Warrington', 'Warrington'), ('Warwickshire', 'Warwickshire'), ('West Midlands', 'West Midlands'), ('West Sussex', 'West Sussex'), ('West Yorkshire', 'West Yorkshire'), ('Wiltshire', 'Wiltshire'), ('Worcestershire', 'Worcestershire'), ('York', 'York'), ('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Down', 'Down'), ('Fermanagh', 'Fermanagh'), ('Londonderry', 'Londonderry'), ('Tyrone', 'Tyrone'), ('Blaenau Gwent', 'Blaenau Gwent'), ('Bridgend', 'Bridgend'), ('Caerphilly', 'Caerphilly'), ('Cardiff', 'Cardiff'), ('Carmarthenshire', 'Carmarthenshire'), ('Ceredigion', 'Ceredigion'), ('Conwy', 'Conwy'), ('Denbighshire', 'Denbighshire'), ('Flintshire', 'Flintshire'), ('Gwynedd', 'Gwynedd'), ('Isle of Anglesey', 'Isle of Anglesey'), ('Merthyr Tydfil', 'Merthyr Tydfil'), ('Monmouthshire', 'Monmouthshire'), ('Neath Port Talbot', 'Neath Port Talbot'), ('Newport', 'Newport'), ('Pembrokeshire', 'Pembrokeshire'), ('Powys', 'Powys'), ('Rhondda Cynon Taf', 'Rhondda Cynon Taf'), ('Swansea', 'Swansea'), ('Torfaen', 'Torfaen'), ('Vale of Glamorgan', 'Vale of Glamorgan'), ('Wrexham', 'Wrexham'), ('Aberdeen City', 'Aberdeen City'), ('Aberdeenshire', 'Aberdeenshire'), ('Angus', 'Angus'), ('Argyll and Bute', 'Argyll and Bute'), ('Clackmannanshire', 'Clackmannanshire'), ('Dumfries and Galloway', 'Dumfries and Galloway'), ('Dundee City', 'Dundee City'), ('East Ayrshire', 'East Ayrshire'), ('East Dunbartonshire', 'East Dunbartonshire'), ('East Lothian', 'East Lothian'), ('East Renfrewshire', 'East Renfrewshire'), ('Edinburgh, City of ', 'Edinburgh, City of'), ('Falkirk', 'Falkirk'), ('Fife', 'Fife'), ('Glasgow City', 'Glasgow City'), ('Highland', 'Highland'), ('Inverclyde', 'Inverclyde'), ('Midlothian', 'Midlothian'), ('Moray', 'Moray'), ('North Ayrshire', 'North Ayrshire'), ('North Lanarkshire', 'North Lanarkshire'), ('Perth and Kinross', 'Perth and Kinross'), ('Renfrewshire', 'Renfrewshire'), ('Scottish Borders', 'Scottish Borders'), ('South Ayrshire', 'South Ayrshire'), ('South Lanarkshire', 'South Lanarkshire'), ('Stirling', 'Stirling'), ('West Dunbartonshire', 'West Dunbartonshire'), ('West Lothian', 'West Lothian'), ('Na h-Eileanan Siar', 'Na h-Eileanan Siar'), ('Orkney Islands', 'Orkney Islands'), ('Shetland Islands', 'Shetland Islands')], max_length=100, null=True, verbose_name='County'),
        ),
    ]
