# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 08:01
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0007_usersetting_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('effort', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('tags', models.ManyToManyField(blank=True, to='workmate.Tag')),
            ],
            options={
                'ordering': ('title',),
            },
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
