# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:55
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion


def add_default_states(apps, schema_editor):
    model = apps.get_model("workmate", "StoryState")
    model.onsite.get_or_create(title='Unstarted')


def add_default_types(apps, schema_editor):
    model = apps.get_model("workmate", "StoryType")
    model.onsite.get_or_create(title='Feature')


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0008_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('title',),
            },
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RunPython(
            code=add_default_states,
        ),
        migrations.CreateModel(
            name='StoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('site', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('title',),
            },
            managers=[
                ('onsite', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RunPython(
            code=add_default_types,
        ),
        migrations.AddField(
            model_name='story',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workmate.StoryState'),
        ),
        migrations.AddField(
            model_name='story',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='workmate.StoryTask'),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workmate.StoryType'),
        ),
    ]
