# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0009_story_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tasks',
        ),
        migrations.AddField(
            model_name='storytask',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workmate.Story'),
            preserve_default=False,
        ),
    ]
