# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0010_story_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storytask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
