# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0011_story_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='icebox',
            field=models.BooleanField(default=True),
        ),
    ]
