# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0012_story_icebox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='story',
            name='order',
            field=models.DecimalField(decimal_places=8, default=100, max_digits=16),
            preserve_default=False,
        ),
    ]
