# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workmate', '0014_story_state_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
            preserve_default=False,
        ),
    ]
