# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0016_remove_icebox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storytype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='storytype',
            name='icon',
            field=models.CharField(blank=True, help_text='Accepts either a <a href="http://getbootstrap.com/components/">bootstrap glyphicon</a> or <a href="http://fontawesome.io/icons/">fontawesome</a> icon class.ie "fa fa-bug" or "glyphicon glyphicon-tags" etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storytype',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
