# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmate', '0017_story_type_icon_and_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
