from setuptools import setup, find_packages

setup(
    name='workmate',
    version='0.0.1',
    description='Workmate',
    long_description=open('README.rst').read(),
    author='Stuart George',
    author_email='stuart.bigmassa@gmail.com',
    url='https://github.com/bigmassa/workmate',
    download_url='https://pypi.python.org/pypi/',
    license='MIT',
    packages=find_packages(exclude=('example', 'tests')),
    install_requires=[
        'Django>=1.8,<1.10',
        'django-admin-sortable2>=0.6.4',
        'django-appconf>=1.0.2',
        'django-bootstrap3>=7.0.1',
        'django-classy-tags>=0.7',
        'django-localflavor>=1.2',
        'django-phonenumber-field>=1.0.0',
        'django-reversion>=1.10.0',
        'django-tastypie>=0.13.3',
        'requests>=2.9.1'
    ],
    include_package_data=True,
    keywords=['workmate', ],
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 1.8',
        'Framework :: Django :: 1.9',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
    ],
)
